# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.6
_src_path: gh:hexdoc-dev/hexdoc-mod-template
add_gitignore: false
add_vscode: false
advanced: true
author: TechTastic
base_book_url: https://techtastic.github.io/HexxySkies/
book_id: hexcasting:thehexbook
capitalize_platforms: false
default_branch: master
github_repo: HexxySkies
gradle_minecraft_version_key: minecraft_version
gradle_mod_version_key: mod_version
mod_display_name: Hexxy Skies
modid: hexxyskies
multiloader: true
plugin_ModPlugin_classname: HexxySkiesModPlugin
plugin_name: hexdoc-hexxyskies
plugin_pluggy_classname: HexxySkiesPlugin
plugin_root: doc
plugin_slug: hexdoc_hexxyskies
